apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "labid.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "labid.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "labid.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
