{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "labid.fullname" . }}
  labels:
    {{- include "labid.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gateways:
    - {{ .Values.ingress.gateway }}
  hosts:
    - {{ .Values.ingress.host }}
  http:
  - match:
    - uri:
        prefix: /jwks
    - uri:
        prefix: /.well-known
    name: labid
    route:
    - destination:
        host: {{ include "labid.fullname" . }}
{{- end }}
